const BASIC_INFO = {
  "stockBasicInfo": {
      "stockCode": "000001.SZ",
      "stockShortName": "平安银行",
      "entityName": "平安银行股份有限公司",
      "industryName": "银行",
      "plateName": "主板",
      "listingStatus": "正常上市",
      "issuingSystem": "审批制",
      "isTwoFinancialTargets": 1,
      "isMarginSecurities": 0,
      "area": "广东省",
      "enterpriseNature": "其他",
      "listedDate": 670608000000,
      "currentSharePrice": null,
      "chgRatio": null,
      "concept": null
  },
  "publicOpinionAndStockPriceTrend": {
      "series": [
          {
              "type": "line",
              "data": [
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null
              ]
          },
          {
              "type": "line",
              "data": [
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null
              ]
          },
          {
              "type": "line",
              "data": [
                  12.48,
                  12.56,
                  12.69,
                  12.69,
                  12.69,
                  12.93,
                  13,
                  12.85,
                  12.75,
                  12.5,
                  12.5,
                  12.5,
                  12.1,
                  12.28,
                  12.12,
                  12.26,
                  12.55,
                  12.55,
                  12.55,
                  12.55,
                  12.55,
                  12.55,
                  12.73,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91,
                  12.91
              ]
          },
          {
              "type": "bar",
              "data": [
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  []
              ]
          },
          {
              "type": "bar",
              "data": [
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  [],
                  []
              ]
          }
      ],
      "xaxis": [
          "2023.04.12",
          "2023.04.13",
          "2023.04.14",
          "2023.04.15",
          "2023.04.16",
          "2023.04.17",
          "2023.04.18",
          "2023.04.19",
          "2023.04.20",
          "2023.04.21",
          "2023.04.22",
          "2023.04.23",
          "2023.04.24",
          "2023.04.25",
          "2023.04.26",
          "2023.04.27",
          "2023.04.28",
          "2023.04.29",
          "2023.04.30",
          "2023.05.01",
          "2023.05.02",
          "2023.05.03",
          "2023.05.04",
          "2023.05.05",
          "2023.05.06",
          "2023.05.07",
          "2023.05.08",
          "2023.05.09",
          "2023.05.10",
          "2023.05.11",
          "2023.05.12",
          "2023.05.13",
          "2023.05.14",
          "2023.05.15",
          "2023.05.16",
          "2023.05.17",
          "2023.05.18",
          "2023.05.19",
          "2023.05.20",
          "2023.05.21",
          "2023.05.22",
          "2023.05.23",
          "2023.05.24",
          "2023.05.25",
          "2023.05.26",
          "2023.05.27",
          "2023.05.28",
          "2023.05.29",
          "2023.05.30",
          "2023.05.31",
          "2023.06.01",
          "2023.06.02",
          "2023.06.03",
          "2023.06.04",
          "2023.06.05",
          "2023.06.06",
          "2023.06.07",
          "2023.06.08",
          "2023.06.09",
          "2023.06.10",
          "2023.06.11",
          "2023.06.12",
          "2023.06.13",
          "2023.06.14",
          "2023.06.15",
          "2023.06.16",
          "2023.06.17",
          "2023.06.18",
          "2023.06.19",
          "2023.06.20",
          "2023.06.21",
          "2023.06.22",
          "2023.06.23",
          "2023.06.24",
          "2023.06.25",
          "2023.06.26",
          "2023.06.27",
          "2023.06.28",
          "2023.06.29",
          "2023.06.30",
          "2023.07.01",
          "2023.07.02",
          "2023.07.03",
          "2023.07.04",
          "2023.07.05",
          "2023.07.06",
          "2023.07.07",
          "2023.07.08",
          "2023.07.09",
          "2023.07.10",
          "2023.07.11",
          "2023.07.12",
          "2023.07.13",
          "2023.07.14",
          "2023.07.15",
          "2023.07.16",
          "2023.07.17",
          "2023.07.18",
          "2023.07.19",
          "2023.07.20",
          "2023.07.21",
          "2023.07.22",
          "2023.07.23",
          "2023.07.24",
          "2023.07.25",
          "2023.07.26",
          "2023.07.27",
          "2023.07.28",
          "2023.07.29",
          "2023.07.30",
          "2023.07.31",
          "2023.08.01",
          "2023.08.02",
          "2023.08.03",
          "2023.08.04",
          "2023.08.05",
          "2023.08.06",
          "2023.08.07",
          "2023.08.08",
          "2023.08.09",
          "2023.08.10",
          "2023.08.11",
          "2023.08.12",
          "2023.08.13",
          "2023.08.14",
          "2023.08.15",
          "2023.08.16",
          "2023.08.17",
          "2023.08.18",
          "2023.08.19",
          "2023.08.20",
          "2023.08.21",
          "2023.08.22",
          "2023.08.23",
          "2023.08.24",
          "2023.08.25",
          "2023.08.26",
          "2023.08.27",
          "2023.08.28",
          "2023.08.29",
          "2023.08.30",
          "2023.08.31",
          "2023.09.01",
          "2023.09.02",
          "2023.09.03",
          "2023.09.04",
          "2023.09.05",
          "2023.09.06",
          "2023.09.07",
          "2023.09.08",
          "2023.09.09",
          "2023.09.10",
          "2023.09.11",
          "2023.09.12",
          "2023.09.13",
          "2023.09.14",
          "2023.09.15",
          "2023.09.16",
          "2023.09.17",
          "2023.09.18",
          "2023.09.19",
          "2023.09.20",
          "2023.09.21",
          "2023.09.22",
          "2023.09.23",
          "2023.09.24",
          "2023.09.25",
          "2023.09.26",
          "2023.09.27",
          "2023.09.28",
          "2023.09.29",
          "2023.09.30",
          "2023.10.01",
          "2023.10.02",
          "2023.10.03",
          "2023.10.04",
          "2023.10.05",
          "2023.10.06",
          "2023.10.07",
          "2023.10.08",
          "2023.10.09"
      ]
  },
  "negativeAndWarningSignal": {
      "series": [
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": 3,
              "data": [
                  {
                      "id": 32,
                      "originalId": 2809155,
                      "newsTitle": "频繁违规被罚、员工金融犯罪，平安银行“蒙眼狂奔”后遗症显现",
                      "newsSource": "财富号",
                      "newsTime": 1684627200000,
                      "importantInfo": "一般关注",
                      "newsText": null,
                      "tag": "#负面新闻# #监管预警-行政处罚# ",
                      "originalCreatedAt": null
                  }
              ]
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          },
          {
              "type": null,
              "data": []
          }
      ],
      "xaxis": [
          "2023.04.12",
          "2023.04.13",
          "2023.04.14",
          "2023.04.15",
          "2023.04.16",
          "2023.04.17",
          "2023.04.18",
          "2023.04.19",
          "2023.04.20",
          "2023.04.21",
          "2023.04.22",
          "2023.04.23",
          "2023.04.24",
          "2023.04.25",
          "2023.04.26",
          "2023.04.27",
          "2023.04.28",
          "2023.04.29",
          "2023.04.30",
          "2023.05.01",
          "2023.05.02",
          "2023.05.03",
          "2023.05.04",
          "2023.05.05",
          "2023.05.06",
          "2023.05.07",
          "2023.05.08",
          "2023.05.09",
          "2023.05.10",
          "2023.05.11",
          "2023.05.12",
          "2023.05.13",
          "2023.05.14",
          "2023.05.15",
          "2023.05.16",
          "2023.05.17",
          "2023.05.18",
          "2023.05.19",
          "2023.05.20",
          "2023.05.21",
          "2023.05.22",
          "2023.05.23",
          "2023.05.24",
          "2023.05.25",
          "2023.05.26",
          "2023.05.27",
          "2023.05.28",
          "2023.05.29",
          "2023.05.30",
          "2023.05.31",
          "2023.06.01",
          "2023.06.02",
          "2023.06.03",
          "2023.06.04",
          "2023.06.05",
          "2023.06.06",
          "2023.06.07",
          "2023.06.08",
          "2023.06.09",
          "2023.06.10",
          "2023.06.11",
          "2023.06.12",
          "2023.06.13",
          "2023.06.14",
          "2023.06.15",
          "2023.06.16",
          "2023.06.17",
          "2023.06.18",
          "2023.06.19",
          "2023.06.20",
          "2023.06.21",
          "2023.06.22",
          "2023.06.23",
          "2023.06.24",
          "2023.06.25",
          "2023.06.26",
          "2023.06.27",
          "2023.06.28",
          "2023.06.29",
          "2023.06.30",
          "2023.07.01",
          "2023.07.02",
          "2023.07.03",
          "2023.07.04",
          "2023.07.05",
          "2023.07.06",
          "2023.07.07",
          "2023.07.08",
          "2023.07.09",
          "2023.07.10",
          "2023.07.11",
          "2023.07.12",
          "2023.07.13",
          "2023.07.14",
          "2023.07.15",
          "2023.07.16",
          "2023.07.17",
          "2023.07.18",
          "2023.07.19",
          "2023.07.20",
          "2023.07.21",
          "2023.07.22",
          "2023.07.23",
          "2023.07.24",
          "2023.07.25",
          "2023.07.26",
          "2023.07.27",
          "2023.07.28",
          "2023.07.29",
          "2023.07.30",
          "2023.07.31",
          "2023.08.01",
          "2023.08.02",
          "2023.08.03",
          "2023.08.04",
          "2023.08.05",
          "2023.08.06",
          "2023.08.07",
          "2023.08.08",
          "2023.08.09",
          "2023.08.10",
          "2023.08.11",
          "2023.08.12",
          "2023.08.13",
          "2023.08.14",
          "2023.08.15",
          "2023.08.16",
          "2023.08.17",
          "2023.08.18",
          "2023.08.19",
          "2023.08.20",
          "2023.08.21",
          "2023.08.22",
          "2023.08.23",
          "2023.08.24",
          "2023.08.25",
          "2023.08.26",
          "2023.08.27",
          "2023.08.28",
          "2023.08.29",
          "2023.08.30",
          "2023.08.31",
          "2023.09.01",
          "2023.09.02",
          "2023.09.03",
          "2023.09.04",
          "2023.09.05",
          "2023.09.06",
          "2023.09.07",
          "2023.09.08",
          "2023.09.09",
          "2023.09.10",
          "2023.09.11",
          "2023.09.12",
          "2023.09.13",
          "2023.09.14",
          "2023.09.15",
          "2023.09.16",
          "2023.09.17",
          "2023.09.18",
          "2023.09.19",
          "2023.09.20",
          "2023.09.21",
          "2023.09.22",
          "2023.09.23",
          "2023.09.24",
          "2023.09.25",
          "2023.09.26",
          "2023.09.27",
          "2023.09.28",
          "2023.09.29",
          "2023.09.30",
          "2023.10.01",
          "2023.10.02",
          "2023.10.03",
          "2023.10.04",
          "2023.10.05",
          "2023.10.06",
          "2023.10.07",
          "2023.10.08",
          "2023.10.09"
      ]
  }
}

const TABLE_DATA = {
  "total": 1,
  "items": [
      {
          "id": 32,
          "originalId": null,
          "newsTitle": "频繁违规被罚、员工金融犯罪，平安银行“蒙眼狂奔”后遗症显现",
          "newsSource": "财富号",
          "newsTime": 1684627200000,
          "importantInfo": "一般关注",
          "newsText": null,
          "tag": "#负面新闻# #监管预警-行政处罚# ",
          "originalCreatedAt": null
      }
  ]
}

export {
  BASIC_INFO,
  TABLE_DATA
}